import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Plus,Trash2,Upload,FileSpreadsheet,Printer,Eye,Search,UserRound,History,CheckCircle2,Clock3} from 'lucide-react';
import {RtlDatePicker} from '../../components/common.jsx';
import {money,uid,parseAmount,todayISO,displayDate} from '../../utils/appUtils.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const reportCss=`@page{size:A4 portrait;margin:12mm}*{box-sizing:border-box}body{font-family:Cairo,Arial,sans-serif;direction:rtl;color:#0D1B2A;margin:0;background:#fff}.paper{padding:6mm}.head{border-bottom:3px solid #A3B18A;padding:0 0 12px;margin-bottom:14px}.head h1{font-size:20px;margin:0}.head p{margin:4px 0 0;color:#697C70;font-size:11px}.meta{display:flex;justify-content:space-between;gap:12px;border:1px solid #d8d1c5;background:#F6EFE3;border-radius:12px;padding:10px 14px;margin-bottom:14px;font-weight:700}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.summary div{border:1px solid #d8d1c5;border-radius:10px;padding:9px;background:#faf8f3}.summary small{display:block;color:#697C70}.summary strong{display:block;margin-top:3px}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:10px}th{background:#E7EBDD;padding:8px;border:1px solid #cdd4c4}td{padding:8px;border:1px solid #dedbd2;vertical-align:top;overflow-wrap:anywhere}tfoot td{font-weight:800;background:#F6EFE3}.total{font-size:14px;color:#0D1B2A}.done{color:#39724f;font-weight:800}.pending{color:#9b642e;font-weight:800}.supplier-card{border:1px solid #cdd4c4;border-radius:16px;padding:18px}.supplier-card h2{margin-top:0}.supplier-card-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{border:1px solid #e1ddd3;border-radius:10px;padding:9px}.field small{display:block;color:#697C70}.field strong{display:block;margin-top:3px}.empty{text-align:center;color:#697C70;padding:18px}`;

function Preview({html,onClose}){
  const ref=useRef(null);
  return <div className="print-preview-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="print-preview-modal real-preview"><div className="print-preview-toolbar"><strong>معاينة قبل الطباعة</strong><div className="print-preview-actions"><button className="btn primary" onClick={()=>ref.current?.contentWindow?.print()}><Printer size={16}/> طباعة</button><button className="btn" onClick={onClose}>إغلاق</button></div></div><div className="print-preview-stage real-stage"><iframe ref={ref} className="print-preview-frame" title="معاينة" srcDoc={html}/></div></div></div>;
}

function SuppliersPage({state,isEditing=false,onChange,onNotify}){
  const suppliers=state.suppliers||[],transfers=state.supplierTransfers||[];
  const transferDepartments=useMemo(()=>Array.from(new Set([...(state.departments||[]),state.supplierTransferDepartment,...transfers.map(x=>x.department)].map(x=>String(x||'').trim()).filter(Boolean))),[state.departments,state.supplierTransferDepartment,transfers]);
  const [tab,setTab]=useState('suppliers'),[preview,setPreview]=useState(null),[query,setQuery]=useState('');
  const [selectedDate,setSelectedDate]=useState(todayISO),[selectedDepartment,setSelectedDepartment]=useState(()=>state.supplierTransferDepartment||state.departments?.[0]||'');
  const [importRows,setImportRows]=useState([]),[map,setMap]=useState({num:'A',name:'B',iban:'C',from:2,to:''});
  const fileRef=useRef(null);
  useEffect(()=>{if(!selectedDepartment&&transferDepartments[0])setSelectedDepartment(transferDepartments[0]);},[selectedDepartment,transferDepartments]);
  const filtered=useMemo(()=>suppliers.filter(x=>`${x.supplierNumber} ${x.name} ${x.iban}`.toLowerCase().includes(query.toLowerCase())),[suppliers,query]);
  const visibleTransfers=useMemo(()=>transfers.filter(x=>x.date===selectedDate&&(!selectedDepartment||x.department===selectedDepartment)),[transfers,selectedDate,selectedDepartment]);
  const transferSummary=useMemo(()=>({total:visibleTransfers.reduce((n,x)=>n+parseAmount(x.amount),0),done:visibleTransfers.filter(x=>x.status==='transferred').reduce((n,x)=>n+parseAmount(x.amount),0),pending:visibleTransfers.filter(x=>x.status!=='transferred').reduce((n,x)=>n+parseAmount(x.amount),0)}),[visibleTransfers]);

  const patchSupplier=(id,key,value)=>{
    const current=suppliers.find(x=>x.id===id);
    const nextSuppliers=suppliers.map(x=>x.id===id?{...x,[key]:value}:x);
    if(!current||!current.supplierNumber.trim()||!['supplierNumber','name'].includes(key)){onChange({suppliers:nextSuppliers});return;}
    const nextTransfers=transfers.map(x=>x.supplierNumber===current.supplierNumber?{...x,...(key==='supplierNumber'?{supplierNumber:value}:{supplierName:value})}:x);
    onChange({suppliers:nextSuppliers,supplierTransfers:nextTransfers});
  };
  const addSupplier=()=>onChange({suppliers:[...suppliers,{id:uid(),supplierNumber:'',name:'',iban:'',phone:'',email:'',address:'',taxNumber:''}]});
  const deleteSupplier=id=>onChange({suppliers:suppliers.filter(x=>x.id!==id)});
  const addTransfer=()=>{
    if(!selectedDepartment){onNotify?.({tone:'error',title:'اختر القسم أولًا',message:'حدد القسم الذي يطلب التحويل ثم أضف المورد.'});return;}
    onChange({supplierTransferDepartment:selectedDepartment,supplierTransfers:[...transfers,{id:uid(),supplierNumber:'',supplierName:'',amount:'',date:selectedDate,department:selectedDepartment,status:'pending',transferredAt:null}]});
  };
  const patchTransfer=(id,key,value)=>{
    const next=transfers.map(x=>{
      if(x.id!==id)return x;
      const row={...x,[key]:value};
      if(key==='supplierNumber'){
        const found=suppliers.find(s=>s.supplierNumber.trim()===String(value).trim());
        row.supplierName=found?.name||'';
      }
      return row;
    });
    onChange({supplierTransfers:next});
  };
  const toggleTransferred=row=>{
    const transferred=row.status!=='transferred';
    onChange({supplierTransfers:transfers.map(x=>x.id===row.id?{...x,status:transferred?'transferred':'pending',transferredAt:transferred?new Date().toISOString():null}:x)});
  };
  const deleteTransfer=id=>onChange({supplierTransfers:transfers.filter(x=>x.id!==id)});
  const supplierForTransfer=row=>String(row.supplierNumber||'').trim()?suppliers.find(x=>String(x.supplierNumber).trim()===String(row.supplierNumber).trim()):null;

  const supplierHtml=(one=null)=>{
    const rows=one?[one]:suppliers;
    return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><style>${reportCss}</style></head><body><div class="paper">${one?`<div class="supplier-card"><h2>كارت المورد</h2><div class="supplier-card-grid"><div class="field"><small>رقم المورد</small><strong>${esc(one.supplierNumber)||'—'}</strong></div><div class="field"><small>اسم المورد</small><strong>${esc(one.name)||'—'}</strong></div><div class="field"><small>IBAN</small><strong>${esc(one.iban)||'—'}</strong></div><div class="field"><small>الهاتف</small><strong>${esc(one.phone)||'—'}</strong></div><div class="field"><small>البريد</small><strong>${esc(one.email)||'—'}</strong></div><div class="field"><small>الرقم الضريبي</small><strong>${esc(one.taxNumber)||'—'}</strong></div><div class="field" style="grid-column:1/-1"><small>العنوان</small><strong>${esc(one.address)||'—'}</strong></div></div></div>`:`<div class="head"><h1>بيان الموردين</h1><p>قائمة بيانات الموردين</p></div><table><thead><tr><th style="width:8%">م</th><th style="width:22%">رقم المورد</th><th>اسم المورد</th><th style="width:35%">رقم حساب IBAN المورد</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.supplierNumber)}</td><td>${esc(x.name)}</td><td>${esc(x.iban)}</td></tr>`).join('')}</tbody></table>`}</div></body></html>`;
  };
  const transfersHtml=()=>`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><style>${reportCss}</style></head><body><div class="paper"><div class="head"><h1>بيان تحويلات الموردين</h1><p>التحويلات المسجلة حسب التاريخ والقسم</p></div><div class="meta"><span>القسم: ${esc(selectedDepartment||'كل الأقسام')}</span><span>التاريخ: ${esc(displayDate(selectedDate))}</span></div><div class="summary"><div><small>إجمالي المطلوب</small><strong>${money.format(transferSummary.total)} ر.س</strong></div><div><small>تم التحويل</small><strong>${money.format(transferSummary.done)} ر.س</strong></div><div><small>متبقي</small><strong>${money.format(transferSummary.pending)} ر.س</strong></div></div><table><thead><tr><th style="width:7%">م</th><th style="width:18%">رقم المورد</th><th>اسم المورد</th><th style="width:20%">المبلغ</th><th style="width:18%">الحالة</th></tr></thead><tbody>${visibleTransfers.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.supplierNumber)}</td><td>${esc(x.supplierName)}</td><td>${money.format(parseAmount(x.amount))} ر.س</td><td class="${x.status==='transferred'?'done':'pending'}">${x.status==='transferred'?'تم التحويل':'مطلوب التحويل'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">لا توجد تحويلات في هذا التاريخ والقسم</td></tr>'}</tbody><tfoot><tr><td colspan="3">الإجمالي العام</td><td class="total">${money.format(transferSummary.total)} ر.س</td><td></td></tr></tfoot></table></div></body></html>`;
  const supplierStatementHtml=supplier=>{
    const supplierNumber=String(supplier.supplierNumber||'').trim();
    const history=(supplierNumber?transfers.filter(x=>String(x.supplierNumber).trim()===supplierNumber):[]).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));
    const requested=history.reduce((n,x)=>n+parseAmount(x.amount),0),completed=history.filter(x=>x.status==='transferred').reduce((n,x)=>n+parseAmount(x.amount),0);
    return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><style>${reportCss}</style></head><body><div class="paper"><div class="head"><h1>كشف حساب المورد</h1><p>سجل التحويلات حسب التاريخ والقسم</p></div><div class="meta"><span>رقم المورد: ${esc(supplier.supplierNumber)||'—'}</span><span>اسم المورد: ${esc(supplier.name)||'—'}</span></div><div class="summary"><div><small>إجمالي المطلوب</small><strong>${money.format(requested)} ر.س</strong></div><div><small>تم تحويله</small><strong>${money.format(completed)} ر.س</strong></div><div><small>المتبقي</small><strong>${money.format(requested-completed)} ر.س</strong></div></div><table><thead><tr><th style="width:8%">م</th><th style="width:18%">التاريخ</th><th>القسم</th><th style="width:20%">المبلغ</th><th style="width:20%">الحالة</th></tr></thead><tbody>${history.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(displayDate(x.date))}</td><td>${esc(x.department)||'—'}</td><td>${money.format(parseAmount(x.amount))} ر.س</td><td class="${x.status==='transferred'?'done':'pending'}">${x.status==='transferred'?'تم التحويل':'مطلوب التحويل'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">لا توجد تحويلات مسجلة لهذا المورد</td></tr>'}</tbody></table></div></body></html>`;
  };

  const handleFile=async file=>{if(!file)return;const XLSX=await import('xlsx');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];setImportRows(XLSX.utils.sheet_to_json(ws,{header:1,defval:''}));onNotify?.({tone:'success',title:'تم قراءة ملف Excel',message:'حدد الأعمدة ونطاق الصفوف ثم اضغط استيراد.'});};
  const colIndex=letters=>{let n=0;for(const c of String(letters).toUpperCase().replace(/[^A-Z]/g,''))n=n*26+c.charCodeAt(0)-64;return Math.max(0,n-1);};
  const applyImport=()=>{if(!importRows.length)return;const from=Math.max(1,Number(map.from)||1)-1,to=map.to?Math.min(importRows.length,Number(map.to)):importRows.length;const items=importRows.slice(from,to).map(r=>({id:uid(),supplierNumber:String(r[colIndex(map.num)]??'').trim(),name:String(r[colIndex(map.name)]??'').trim(),iban:String(r[colIndex(map.iban)]??'').trim(),phone:'',email:'',address:'',taxNumber:''})).filter(x=>x.supplierNumber||x.name||x.iban);const existing=new Set(suppliers.map(x=>x.supplierNumber.trim()).filter(Boolean));const added=items.filter(x=>!x.supplierNumber||!existing.has(x.supplierNumber));onChange({suppliers:[...suppliers,...added]});setImportRows([]);onNotify?.({tone:'success',title:'تم استيراد الموردين',message:`تمت إضافة ${added.length} صف من Excel.`});};
  const exportExcel=async()=>{const XLSX=await import('xlsx');const data=suppliers.map((x,i)=>({'م':i+1,'رقم المورد':x.supplierNumber,'اسم المورد':x.name,'IBAN':x.iban,'الهاتف':x.phone,'البريد الإلكتروني':x.email,'العنوان':x.address,'الرقم الضريبي':x.taxNumber}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'الموردين');XLSX.writeFile(wb,'بيان الموردين.xlsx');};

  return <section className="page suppliers-page">
    <div className="suppliers-hero"><div><h2>بيان الموردين</h2><p>إدارة بيانات الموردين وسجل التحويلات حسب التاريخ والقسم</p></div><div className="suppliers-tabs"><button className={tab==='suppliers'?'active':''} onClick={()=>setTab('suppliers')}>بيانات الموردين</button><button className={tab==='transfers'?'active':''} onClick={()=>setTab('transfers')}>الحوالات المطلوبة</button></div></div>
    {tab==='suppliers'?<>
      <div className="supplier-toolbar"><div className="supplier-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث برقم أو اسم المورد أو IBAN"/></div><button disabled={!isEditing} onClick={addSupplier}><Plus/> إضافة مورد</button><button disabled={!isEditing} onClick={()=>fileRef.current?.click()}><Upload/> استيراد Excel</button><input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>handleFile(e.target.files?.[0])}/><button onClick={exportExcel}><FileSpreadsheet/> تصدير Excel</button><button onClick={()=>setPreview(supplierHtml())}><Eye/> معاينة التقرير</button></div>
      {importRows.length>0&&<div className="supplier-import-box"><strong>الاستيراد الذكي من Excel</strong><div><label>عمود رقم المورد<input value={map.num} onChange={e=>setMap({...map,num:e.target.value})}/></label><label>عمود الاسم<input value={map.name} onChange={e=>setMap({...map,name:e.target.value})}/></label><label>عمود IBAN<input value={map.iban} onChange={e=>setMap({...map,iban:e.target.value})}/></label><label>من صف<input type="number" value={map.from} onChange={e=>setMap({...map,from:e.target.value})}/></label><label>إلى صف<input type="number" value={map.to} onChange={e=>setMap({...map,to:e.target.value})} placeholder="آخر الملف"/></label><button onClick={applyImport}>استيراد المحدد</button></div></div>}
      <div className="supplier-table-wrap"><table className="supplier-table"><thead><tr><th>م</th><th>رقم المورد</th><th>اسم المورد</th><th>رقم حساب IBAN المورد</th><th>الهاتف</th><th>الإيميل</th><th>العنوان</th><th>الرقم الضريبي</th><th>الإجراءات</th></tr></thead><tbody>{filtered.map((x,i)=><tr key={x.id}><td>{i+1}</td>{['supplierNumber','name','iban','phone','email','address','taxNumber'].map(k=><td key={k}><input disabled={!isEditing} value={x[k]} onChange={e=>patchSupplier(x.id,k,e.target.value)}/></td>)}<td className="supplier-actions"><button onClick={()=>setPreview(supplierHtml(x))} title="كارت المورد"><UserRound/></button><button className="supplier-statement-btn" onClick={()=>setPreview(supplierStatementHtml(x))} title="كشف حساب المورد"><History/><span>كشف الحساب</span></button>{isEditing&&<button onClick={()=>deleteSupplier(x.id)} title="حذف المورد"><Trash2/></button>}</td></tr>)}</tbody></table></div>
    </>:<>
      <div className="supplier-transfer-head"><div className="supplier-transfer-filters"><label><span>تاريخ التحويلات</span><RtlDatePicker value={selectedDate} onChange={setSelectedDate}/></label><label><span>القسم</span><select value={selectedDepartment} onChange={e=>setSelectedDepartment(e.target.value)}><option value="">اختر القسم</option>{transferDepartments.map(x=><option key={x}>{x}</option>)}</select></label></div><div><button disabled={!isEditing||!selectedDepartment} onClick={addTransfer}><Plus/> إضافة تحويل لهذا اليوم</button><button onClick={()=>setPreview(transfersHtml())}><Eye/> معاينة وطباعة</button></div></div>
      <div className="supplier-transfer-summary"><div><span>إجمالي المطلوب</span><strong>{money.format(transferSummary.total)} ر.س</strong></div><div className="done"><span>تم التحويل</span><strong>{money.format(transferSummary.done)} ر.س</strong></div><div className="pending"><span>متبقي للتحويل</span><strong>{money.format(transferSummary.pending)} ر.س</strong></div></div>
      <div className="supplier-table-wrap"><table className="supplier-table transfer-table"><thead><tr><th>م</th><th>التاريخ</th><th>القسم</th><th>رقم المورد</th><th>اسم المورد</th><th>المبلغ</th><th>حالة التحويل</th><th></th></tr></thead><tbody>{visibleTransfers.length?visibleTransfers.map((x,i)=><tr key={x.id}><td>{i+1}</td><td>{displayDate(x.date)}</td><td>{x.department}</td><td><input disabled={!isEditing} value={x.supplierNumber} onChange={e=>patchTransfer(x.id,'supplierNumber',e.target.value)} list="supplier-number-list"/></td><td><div className="transfer-supplier-cell"><input disabled value={x.supplierName}/><button disabled={!supplierForTransfer(x)} onClick={()=>setPreview(supplierStatementHtml(supplierForTransfer(x)))} title="فتح كشف حساب المورد"><History/><span>كشف</span></button></div></td><td><input disabled={!isEditing} inputMode="decimal" value={x.amount} onChange={e=>patchTransfer(x.id,'amount',e.target.value.replace(/[^0-9.,]/g,''))}/></td><td><button disabled={!isEditing} className={`supplier-transfer-status ${x.status==='transferred'?'done':'pending'}`} onClick={()=>toggleTransferred(x)}>{x.status==='transferred'?<><CheckCircle2/> تم التحويل</>:<><Clock3/> مطلوب التحويل</>}</button></td><td>{isEditing&&<button className="row-delete" onClick={()=>deleteTransfer(x.id)}><Trash2/></button>}</td></tr>):<tr><td colSpan="8"><div className="supplier-transfer-empty"><History/><strong>لا توجد تحويلات لهذا التاريخ والقسم</strong><span>أضف تحويلات اليوم وستظل التحويلات القديمة محفوظة في تواريخها.</span></div></td></tr>}</tbody><tfoot><tr><td colSpan="5">إجمالي {displayDate(selectedDate)} — {selectedDepartment||'كل الأقسام'}</td><td><strong>{money.format(transferSummary.total)} ر.س</strong></td><td colSpan="2"></td></tr></tfoot></table><datalist id="supplier-number-list">{suppliers.map(s=><option key={s.id} value={s.supplierNumber}>{s.name}</option>)}</datalist></div>
    </>}
    {preview&&<Preview html={preview} onClose={()=>setPreview(null)}/>}
  </section>;
}

export default SuppliersPage;
